<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJodUjGy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJodUjGy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJodUjGy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJodUjGy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJodUjGy\App_KernelDevDebugContainer([
    'container.build_hash' => 'JodUjGy',
    'container.build_id' => '3771b868',
    'container.build_time' => 1695394806,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJodUjGy');
